// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_llO2tie-I68nMYLeKLmhbo2u43vMY10',
    appId: '1:652394587695:web:db0df3097accf96edfc8da',
    messagingSenderId: '652394587695',
    projectId: 'flutter-mobile-chatapp',
    authDomain: 'flutter-mobile-chatapp.firebaseapp.com',
    storageBucket: 'flutter-mobile-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4qiT_E5zMyDIR1IapmKOgx7OGlyUJe2E',
    appId: '1:652394587695:android:67bb781f3d0ff74edfc8da',
    messagingSenderId: '652394587695',
    projectId: 'flutter-mobile-chatapp',
    storageBucket: 'flutter-mobile-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrhcYIYDXsGrTo_JYcL312fE2_jkDKOLc',
    appId: '1:652394587695:ios:a27100fd7d3758addfc8da',
    messagingSenderId: '652394587695',
    projectId: 'flutter-mobile-chatapp',
    storageBucket: 'flutter-mobile-chatapp.firebasestorage.app',
    iosClientId: '652394587695-5n0bp4hijgg0rq27nm8862kurtatkqd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAndroidChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrhcYIYDXsGrTo_JYcL312fE2_jkDKOLc',
    appId: '1:652394587695:ios:a27100fd7d3758addfc8da',
    messagingSenderId: '652394587695',
    projectId: 'flutter-mobile-chatapp',
    storageBucket: 'flutter-mobile-chatapp.firebasestorage.app',
    iosClientId: '652394587695-5n0bp4hijgg0rq27nm8862kurtatkqd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAndroidChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_llO2tie-I68nMYLeKLmhbo2u43vMY10',
    appId: '1:652394587695:web:06fb246debb8ab9cdfc8da',
    messagingSenderId: '652394587695',
    projectId: 'flutter-mobile-chatapp',
    authDomain: 'flutter-mobile-chatapp.firebaseapp.com',
    storageBucket: 'flutter-mobile-chatapp.firebasestorage.app',
  );

}